services:
  app:
    container_name: app
    image: registry.sedrehgroup.ir/exchange:latest
    restart: 'always'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - main
    volumes:
      - .:/app
    command: /app/entrypoint.sh

  db:
    container_name: database
    image: registry.sedrehgroup.ir/postgres:16-alpine
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - main

  pgadmin:
    container_name: pgadmin
    image: registry.sedrehgroup.ir/pgadmin4
    ports:
      - '5050:80'
    env_file:
      - .env
    networks:
      - main

# volumes:
#   postgres-data:

networks:
  main:

